baseURL = "https://mozhn.dev/"
languageCode = "tr-tr"
title = "Mazlum Özhan "
theme = "paper"
googleAnalytics = "G-QLF1P68R96"

[params]
  github = 'mozhn'

[menu]
  [[menu.main]]
  identifier = ''
  name = 'Blog'
  url = '/'
  weight = -110
  [[menu.main]]
  identifier = 'about'
  name = 'Hakkımda1'
  url = '/about/'
  weight = -100
