baseURL = "https://mozhn.dev/"
theme = "paper"
googleAnalytics = "G-QLF1P68R96"
defaultContentLanguage = "tr"

[languages]
  [languages.tr]
    languageCode = "tr-TR"
    languageName = "Türkçe"
    title = "mazlum"
    weight = 1

    [languages.tr.params]
      github = 'mozhn'
      twitter = 'elfentech'
      description = "Ortaya karışık ilgimi ne çekerse yazıyorum ya da deniyorum"

    [[languages.tr.menu.main]]
      identifier = ''
      name = 'Blog'
      url = '/'
      weight = -110
    [[languages.tr.menu.main]]
      identifier = 'about'
      name = 'Hakkımda'
      url = '/about/'
      weight = -100

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "mazlum"
    weight = 2

    [languages.en.params]
      github = 'mozhn'
      twitter = 'elfentech'
      description = "I write or experiment with whatever catches my interest"

    [[languages.en.menu.main]]
      identifier = ''
      name = 'Blog'
      url = '/en/'
      weight = -110
    [[languages.en.menu.main]]
      identifier = 'about'
      name = 'About'
      url = '/en/about/'
      weight = -100

[params]
  github = 'mozhn'
